name: bibliotheque_app
description: Application Flutter 2 en 1 pour gérer une bibliothèque et des réservations de créneaux
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  sqflite_common_ffi: 2.1.0+2
  path: ^1.8.3
  intl: ^0.18.1
  provider: ^6.1.1
  http: ^1.1.0
  msix: ^3.16.0
  file_picker: ^6.1.1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
